export enum TourNames {
  COCO_BONGO = 'Coco Bongo',
  COCO_BONGO_REGULAR_TICKET = 'Coco Bongo Regular Ticket',
  COCO_BONGO_PREMIUM_TICKET = 'Coco Bongo Premium Ticket',
  COCO_BONGO_GOLDEN_MEMBER = 'Coco Bongo Golden Member',
  COCO_BONGO_FRONT_ROW = 'Coco Bongo Front Row',
  ISLA_SAONA = 'Isla Saona',
  PUNTA_CANA_TOUR_BUGGY = 'Punta Cana Tour Buggy',
  MONKEYLAND_TOUR = 'Monkeyland Tour',
  SUPREME_SAFARI_TOUR = 'Supreme Safari Tour',
  PUNTA_CANA_TOUR_HIGUEY = 'Punta Cana Tour Higuey',
  PUNTA_CANA_TOUR_SANTO_DOMINGO = 'Punta Cana Tour Santo Domingo',
  TOUR_HORSE = 'Tour Horse',
  PUNTA_CANA_TOUR_ZIP_LINE_PARK = 'Punta Cana Tour Zip Line Park',
  LA_HACIENDA_PARK = 'La Hacienda Park',
  PARTY_BOAT_TOUR = 'Party Boat Tour',
}

export const ToursArray = [
  'Coco Bongo',
  'Coco Bongo Regular Ticket',
  'Coco Bongo Premium Ticket',
  'Coco Bongo Golden Member',
  'Coco Bongo Front Row',
  'Isla Saona',
  'Punta Cana Tour Buggy',
  'Monkeyland Tour',
  'Supreme Safari Tour',
  'Punta Cana Tour Higuey',
  'Punta Cana Tour Santo Domingo',
  'Tour Horse',
  'Punta Cana Tour Zip Line Park',
  'La Hacienda Park',
  'Party Boat Tour',
];
